#!/bin/sh

set -e

exec 3>&1 1>&2

INPUT='/tmp/input'
RESPONSE='/tmp/response'
cat > "${INPUT}" <&0 

BOT_TOKEN=$(jq -r '.source.bot_token // ""' "${INPUT}")
COMMAND=$(  jq -r '.source.command   // ""' "${INPUT}")
CHAT_ID=$(  jq -r '.source.chat_id   // ""' "${INPUT}")
ADMINS=$(   jq -r '.source.admins    // []' "${INPUT}")

ERROR_MSG="Is not defined"
[[ "${BOT_TOKEN:?$ERROR_MSG}" ]]
[[ "${CHAT_ID:?$ERROR_MSG}"   ]]
[[ "${COMMAND}" ]] || echo "[Warning] Command $ERROR_MSG"

CHAT_ID_CHECK="select( .message.chat.id | contains(${CHAT_ID})) |"
if [[ "${ADMINS}" == "[]" ]]; then
    ADMINS_CHECK=""
else
    ADMINS_CHECK="select( [.message.from.username] | inside(${ADMINS})) |"
fi
COMMAND_CHECK="select( .message.text | tostring | contains(\"${COMMAND}\")) |"

curl -s -X GET "https://api.telegram.org/bot${BOT_TOKEN}/getUpdates" > "${RESPONSE}"
jq "[ .result[] |
      ${CHAT_ID_CHECK}
      ${ADMINS_CHECK}
      ${COMMAND_CHECK}
      .message.message_id | tostring // \"none\" |
      { ref: . } ]" "${RESPONSE}" >&3

