#!/bin/bash

INPUT='/tmp/input'
OUTPUT='/tmp/output'

# write STDIN to file
#{"source":{"bot":"","chat_id":""},"params":{"message":""}}
cat > "${INPUT}" <&0 

BOT_TOKEN=$(jq -r '.source.bot_token // ""' <"${INPUT}")
CHAT_ID=$(jq -r '.source.chat_id // ""' <"${INPUT}")
MESSAGE=$(jq -r '.params.message // ""' <"${INPUT}")

RESPONSE=$(curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
                -d "chat_id=${CHAT_ID}" \
                -d "text=<b>${MESSAGE}</b>%0A<b>Pipeline: </b>${BUILD_PIPELINE_NAME}%0A<b>Job: </b>${BUILD_JOB_NAME}%0A<b>Build number: </b>${BUILD_NAME}" \
                -d "parse_mode=html")

jq -r '. // ""' <<<"${RESPONSE}" 1>&2

OUTPUT_STRING='{ "version": { "ref": "none"} }'
echo "${OUTPUT_STRING}"

# Exit status
#grep -q '"ok":true' <<<"${RESPONSE}" || exit 1

